### PR TITLE
Port gpsp to PSP for RetroArch

### PR DESCRIPTION
**Pull request by fjtrujy**
Make PSP version to render the image it-self instead of using RetroArch

### CODE REVIEW

**Comment by bmaupin** [comment]
@fjtrujy Do you remember what the purpose of this was by any chance? Thanks!

**Comment by fjtrujy** [comment]
Yes @bmaupin ,
The gpSP core for the PSP platform apply color correction to match what PSP expect (most probably because this core was originally developed for PSP). However the RetroArch GFX driver for PSP apply as well color correction.
So this piece of code is to avoid the double color correction.

Thanks

**Comment by bmaupin** [comment]
@fjtrujy I thought I noticed the colours were off 😅

Thanks!

**Comment by bmaupin** [comment]
I just looked at this some more, and apparently this is due to the fact that the PSP has a custom function defined for `convert_palette` in common.h. If the non-custom `convert_palette` is used instead, the colours are fine again.

While that would make the code simpler and avoid custom rendering for the PSP, the PSP rendering implemented here gains an extra 0.5 - 2 FPS by not doing the extra colour conversion.

Nice work!

**Comment by fjtrujy** [comment]
So are you going to create a PR with these changes?

**Comment by bmaupin** [comment]
@fjtrujy Actually what I meant to say was that although my idea would be less code (because we could remove the PSP-specific `convert_palette` and rendering), your code in this PR is actually better because it performs faster on the PSP. So no, I don't plan on submitting a PR for my idea. Thanks!

**Pull request merged**
