### PR TITLE
Add support for RetroArch cheats.

### PR DESCRIPTION
**Pull request by rohit-n**

### CODE REVIEW

**Comment by spaceboydavey** [comment]
Does this add support for encrypted cheat types? I'm so annoyed by GPSP not supporting encrypted cheats. If so can we please speed up merging this?

**Comment by rohit-n** [comment]
I doubt it, but I haven't tried any encrypted cheats. I've only tested this change for searching for cheats in RetroArch's interface.

**Comment by hizzlekizzle** [comment]
@davidgfnet do you have any opinions on this one?

**Comment by davidgfnet** [comment]
gpsp has already support for cheat codes, what does this add exactly? Would be nice to have more info :P

**Comment by rohit-n** [comment]
This commit allows the user to create cheat codes by scanning memory addresses in the RetroArch Quick menu interface. Without this commit, the "Start or Restart Cheat Search" menu option does nothing.

Another benefit of this is that cheats created this way work for the mGBA core, and vice versa.

**Comment by davidgfnet** [comment]
Ah right, was not aware of those options. I'd still recommend using the gpsp cheats but it is indeed useful to be able to search for memory patterns to create new cheats and such.
This was not possible previously but PR #117 fixed that (I assume that's why it never got implemented).
Thanks for contributing this!

**Pull request merged**
