### PR TITLE
Added Goodboy Galaxy rumble support

### PR DESCRIPTION
**Pull request by Ninoh-FOX**

### CODE REVIEW

**Comment by davidgfnet** [comment]
Hey! You have a few more changes there. Is that intentional?

**Comment by Ninoh-FOX** [comment]
Yes, it is the compilation method for the Miyoo mini consoles and the pkmn pinball database in case Gameboy Player is ever supported.  It does not affect the rest of the code.

**Comment by davidgfnet** [comment]
Again, the pokemon pinball game does not use GPIO3 rumble, so it is incorrect to set FLAGS_RUMBLE to it. Only patched games can work with that configuration, are you using some IPS patch?
The right way to do it, would be to implement GameBoy Player rumble support, which will come in the near future.
Thanks!

**Comment by Ninoh-FOX** [comment]
Well, the Goodboy Galaxy work (I know that Pkmn P not work for now)

**Comment by Ninoh-FOX** [comment]
Putout pkmn rumble flag

**Pull request merged**
